<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="transitions" nsURI="http://www.bonitasoft.org/ns/bpm/process/decision/transitions"
    nsPrefix="transitions">
  <eAnnotations source="http://www.eclipse.org/edapt">
    <details key="historyURI" value="process.history"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TakeTransitionAction" eSuperTypes="decision.ecore#//DecisionTableAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="takeTransition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
