<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/bpm/process/decision http://www.bonitasoft.org/ns/bpm/process#//decision">
  <process:MainProcess xmi:id="_RfnEkBvZEeiDyPNAn3pfQA" name="ProcessWithDocument" author="romain" bonitaVersion="9.0.0" bonitaModelVersion="8" configId="ACED000574002550726F6365737357697468446F63756D656E74372E31312E302D303035372E31312E307370">
    <elements xmi:type="process:Pool" xmi:id="_RfnEkRvZEeiDyPNAn3pfQA" name="ProcessWithDocument">
      <elements xmi:type="process:Lane" xmi:id="_RfnEkhvZEeiDyPNAn3pfQA" name="Employee lane" actor="_RfnEuxvZEeiDyPNAn3pfQA">
        <elements xmi:type="process:StartEvent" xmi:id="_RfnEkxvZEeiDyPNAn3pfQA" name="Start1" outgoing="_RfnEuBvZEeiDyPNAn3pfQA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RfnElRvZEeiDyPNAn3pfQA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RfnElhvZEeiDyPNAn3pfQA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RfnElxvZEeiDyPNAn3pfQA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_RfnEmBvZEeiDyPNAn3pfQA" name="Step1" incoming="_RfnEuBvZEeiDyPNAn3pfQA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RfnEmhvZEeiDyPNAn3pfQA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RfnEmxvZEeiDyPNAn3pfQA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RfnEnBvZEeiDyPNAn3pfQA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RfnEnRvZEeiDyPNAn3pfQA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RfnEnhvZEeiDyPNAn3pfQA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RfnEnxvZEeiDyPNAn3pfQA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RfnEoBvZEeiDyPNAn3pfQA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RfnEoRvZEeiDyPNAn3pfQA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_RfnEpBvZEeiDyPNAn3pfQA">
            <targetForm xmi:type="expression:Expression" xmi:id="_RfnEpRvZEeiDyPNAn3pfQA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_RfnEphvZEeiDyPNAn3pfQA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_RfnEpxvZEeiDyPNAn3pfQA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_RfnEshvZEeiDyPNAn3pfQA">
        <targetForm xmi:type="expression:Expression" xmi:id="_RfnEsxvZEeiDyPNAn3pfQA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_RfnEtRvZEeiDyPNAn3pfQA">
        <targetForm xmi:type="expression:Expression" xmi:id="_RfnEthvZEeiDyPNAn3pfQA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RfnEuBvZEeiDyPNAn3pfQA" target="_RfnEmBvZEeiDyPNAn3pfQA" source="_RfnEkxvZEeiDyPNAn3pfQA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RfnEuRvZEeiDyPNAn3pfQA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RfnEuhvZEeiDyPNAn3pfQA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_RfnEuxvZEeiDyPNAn3pfQA" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_RfnEvBvZEeiDyPNAn3pfQA"/>
      <documents xmi:type="process:Document" xmi:id="_XCQNwBvZEeiDyPNAn3pfQA" name="monDoc" defaultValueIdOfDocumentStore="index.html" documentType="INTERNAL">
        <mimeType xmi:type="expression:Expression" xmi:id="_XCQNwRvZEeiDyPNAn3pfQA" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_XCQNwhvZEeiDyPNAn3pfQA" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_XCQNwxvZEeiDyPNAn3pfQA" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RfnEvRvZEeiDyPNAn3pfQA">
        <name xmi:type="expression:Expression" xmi:id="_RfnEvhvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_RfnEvxvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RfnEwBvZEeiDyPNAn3pfQA">
        <name xmi:type="expression:Expression" xmi:id="_RfnEwRvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_RfnEwhvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RfnEwxvZEeiDyPNAn3pfQA">
        <name xmi:type="expression:Expression" xmi:id="_RfnExBvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_RfnExRvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RfnExhvZEeiDyPNAn3pfQA">
        <name xmi:type="expression:Expression" xmi:id="_RfnExxvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_RfnEyBvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RfnEyRvZEeiDyPNAn3pfQA">
        <name xmi:type="expression:Expression" xmi:id="_RfnEyhvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_RfnEyxvZEeiDyPNAn3pfQA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_RfnEzBvZEeiDyPNAn3pfQA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_RfnEzRvZEeiDyPNAn3pfQA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_RfnEzhvZEeiDyPNAn3pfQA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_RfnEzxvZEeiDyPNAn3pfQA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_RfnE0BvZEeiDyPNAn3pfQA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_RfnE0RvZEeiDyPNAn3pfQA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_RfnE0hvZEeiDyPNAn3pfQA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_RfnE0xvZEeiDyPNAn3pfQA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_RfnE1BvZEeiDyPNAn3pfQA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_RfnE1RvZEeiDyPNAn3pfQA" type="Process" element="_RfnEkBvZEeiDyPNAn3pfQA" name="MyDiagram1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_RfnE1hvZEeiDyPNAn3pfQA" type="2007" element="_RfnEkRvZEeiDyPNAn3pfQA">
      <children xmi:type="notation:DecorationNode" xmi:id="_RfnE1xvZEeiDyPNAn3pfQA" type="5008" element="_RfnEkRvZEeiDyPNAn3pfQA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_RfnE2BvZEeiDyPNAn3pfQA" type="7001" element="_RfnEkRvZEeiDyPNAn3pfQA">
        <children xmi:type="notation:Node" xmi:id="_RfnE2RvZEeiDyPNAn3pfQA" type="3007" element="_RfnEkhvZEeiDyPNAn3pfQA">
          <children xmi:type="notation:DecorationNode" xmi:id="_RfnE2hvZEeiDyPNAn3pfQA" type="5007" element="_RfnEkhvZEeiDyPNAn3pfQA"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_RfnE2xvZEeiDyPNAn3pfQA" type="7002" element="_RfnEkhvZEeiDyPNAn3pfQA">
            <children xmi:type="notation:Shape" xmi:id="_RfnE3BvZEeiDyPNAn3pfQA" type="3005" element="_RfnEmBvZEeiDyPNAn3pfQA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RfnE3RvZEeiDyPNAn3pfQA" type="5005" element="_RfnEmBvZEeiDyPNAn3pfQA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RfnE3hvZEeiDyPNAn3pfQA" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RfnE3xvZEeiDyPNAn3pfQA" type="3002" element="_RfnEkxvZEeiDyPNAn3pfQA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_RfnE4BvZEeiDyPNAn3pfQA" type="5024" element="_RfnEkxvZEeiDyPNAn3pfQA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_RfnE4RvZEeiDyPNAn3pfQA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RfnE4hvZEeiDyPNAn3pfQA" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_RfnE4xvZEeiDyPNAn3pfQA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_RfnE5BvZEeiDyPNAn3pfQA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_RfnE5RvZEeiDyPNAn3pfQA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_RfnE5hvZEeiDyPNAn3pfQA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RfnE5xvZEeiDyPNAn3pfQA"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_RfnE6BvZEeiDyPNAn3pfQA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_RfnE6RvZEeiDyPNAn3pfQA" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_RfnE6hvZEeiDyPNAn3pfQA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_RfnE6xvZEeiDyPNAn3pfQA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RfnE7BvZEeiDyPNAn3pfQA" width="1615" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_RfnE7RvZEeiDyPNAn3pfQA"/>
    <edges xmi:type="notation:Connector" xmi:id="_RfnE7hvZEeiDyPNAn3pfQA" type="4001" element="_RfnEuBvZEeiDyPNAn3pfQA" source="_RfnE3xvZEeiDyPNAn3pfQA" target="_RfnE3BvZEeiDyPNAn3pfQA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RfnE7xvZEeiDyPNAn3pfQA" type="6001" element="_RfnEuBvZEeiDyPNAn3pfQA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RfnE8BvZEeiDyPNAn3pfQA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RfnE8RvZEeiDyPNAn3pfQA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RfnE8hvZEeiDyPNAn3pfQA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
