= Eclipse target platform

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Purpose of the target platform

From https://www.vogella.com/tutorials/EclipseTargetPlatform/article.html[Lars Vogel's Eclipse Target Platform article]

The set of plug-ins available for your application development is defined by the plug-ins in your workspace in addition to the plug-ins defined by your target platform. For example, the SWT and JFace plug-ins are typically provided by your target platform. By default, the plug-in installed in your Eclipse IDE installation are used as target platform.

It is good practice to develop and build against a explicit target definition which is stored in a configuration file. This way the plug-in dependencies and the used versions are controlled and specified during the development. A target definition file is typically shared between the developers to ensure that everyone is using the same basis for development. If such a target definition file does not exists, than every developer develops against his version of the Eclipse IDE, which can lead to incompatible changes.

You can activate and switch the target platform in the Eclipse Preferences. Select Window  Preferences  Plug-in Development  Target Platform. It is also possible to active a target platform via its editor via the Set as Active Target Platform link on the first page.

== Updating the target platform

We use these target platform related files:

* `target-platform.tpd` file is the one you should manipulate from your IDE. +
You may use it to define your target platform constraints and use the contextual menus:
    ** Validate
    ** Create Target Definition file
    ** Set as Target Platform
* `target-platform.target` file contains the actual resolved versions and is pointing to the actual p2 update sites. +
You will be using it typically during development phases.

In the `remote_platform.tpd` file, do not explicitly set the plugins/features version unless there is a strict compatiblity requirement. It eases the update process. Often eclipse update sites are already versioned (eg: __https://download.eclipse.org/releases/2022-06__, __https://download.eclipse.org/technology/swtbot/releases/4.0.0/__...).

[WARNING]
====
Once you have regenerated the `target-platform.target` file, you need to add this instructions block in the `BonitaArtifactsModels` location to tell Tycho how to generate feature plugins:

[source, xml]
----
      <instructions><![CDATA[
Bundle-Name:           ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}
version:               ${version_cleanup;${mvnVersion}}
Bundle-SymbolicName:   ${mvnGroupId}.${mvnArtifactId}
Bundle-Version:        ${version}
Import-Package:        *;resolution:=optional
Export-Package:        *;version="${version}";-noimport:=true
DynamicImport-Package: *
]]></instructions>
----

====

== Validating the target platform

The .tpd editor offers validation on the contextual menu.

You may use the `target-platform-validation-plugin` to validate the final target platform:

[source, shell]
----
./mvnw -f releng/target-platform/pom.xml validate -Pvalidate
----

Although this shouldn't be necessary if you validated first in the .tpd editor.
