name: Build Pull Request

on:
  pull_request:
    branches:
      - develop
      - release/*
      - support/*
    paths-ignore:
      - '**/README.md'
      - '.github/**'
      - '!.github/workflows/build-pr.yml'

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Setup Groovy
        # this is required for tests to compile groovy code correctly
        run: |
          sudo apt-get update
          sudo apt-get -y install groovy

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B -ntp verify sonar:sonar -Pjacoco
