name: Build

run-name: Build ${{ github.ref_name }}

on:
  push:
    branches:
      - develop
      - release/*
      - support/*
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/build.yml'
      - '**/*.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Build and deploy
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: ./mvnw -B -ntp deploy sonar:sonar -Pjacoco
